# Generated by Django 4.2 on 2023-04-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_atachment_category_contact_department_device_faculty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atachment',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='laboratory_id',
            new_name='laboratory',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='usage_id',
            new_name='usage',
        ),
    ]
