# Generated by Django 4.2 on 2023-04-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_device_id_atachment_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.faculty'),
        ),
        migrations.AlterField(
            model_name='atachment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.device'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.faculty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.contact'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.department'),
        ),
        migrations.AlterField(
            model_name='device',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.laboratory'),
        ),
        migrations.AlterField(
            model_name='device',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.usage'),
        ),
    ]
