# Generated by Django 4.2 on 2023-04-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_category_faculty_alter_atachment_device_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atachment',
            new_name='Attachment',
        ),
    ]
