# Generated by Django 4.2 on 2023-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_device_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='picture_path',
            field=models.FilePathField(null=True),
        ),
    ]
