# Generated by Django 4.2 on 2023-04-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_device_picture_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='faculty',
        ),
        migrations.AddField(
            model_name='device',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.faculty'),
        ),
    ]
