# Generated by Django 4.2 on 2023-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_category_faculty_device_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.FilePathField(null=True),
        ),
    ]
