# Generated by Django 4.2 on 2023-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='img/managers/male.png', upload_to='img/managers'),
        ),
    ]
