# Generated by Django 4.2 on 2023-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_attachment_path_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='picture_path',
        ),
        migrations.AddField(
            model_name='device',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
