# Generated by Django 4.2 on 2023-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='managers/male.png', max_length=255, upload_to='managers/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='device_pictures/'),
        ),
    ]
