# Generated by Django 4.2 on 2023-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_attachment_file_alter_contact_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laboratories'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='usage',
        ),
        migrations.AddField(
            model_name='device',
            name='usages',
            field=models.ManyToManyField(to='client.usage'),
        ),
    ]
