# Generated by Django 4.2 on 2023-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_attachment_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='logo_en',
            field=models.ImageField(max_length=255, null=True, upload_to='faculties_logo/'),
        ),
    ]
