# Generated by Django 4.2 on 2023-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_faculty_logo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
