# Generated by Django 4.2 on 2023-05-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0024_contact_titles_contact_titles_after"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="picture",
        ),
        migrations.CreateModel(
            name="DevicePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=255, upload_to="device_pictures/"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.device"
                    ),
                ),
            ],
        ),
    ]
