# Generated by Django 4.2 on 2023-05-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_remove_device_picture_devicepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='client.device'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='client.category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='titles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='titles_after',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.faculty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.contact'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.department'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.faculty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.laboratory'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='logo_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='faculties_logo/'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
