# Generated by Django 4.2 on 2023-05-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_alter_attachment_device_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.laboratory'),
        ),
    ]
