# Generated by Django 4.2 on 2023-05-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_alter_device_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.faculty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.department'),
        ),
        migrations.AlterField(
            model_name='device',
            name='usages',
            field=models.ManyToManyField(blank=True, to='client.usage'),
        ),
    ]
