# Generated by Django 4.2 on 2023-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_laboratory_faculty_alter_device_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_partner_organization',
            field=models.BooleanField(default=False),
        ),
    ]
