version: '3.8'

services:

  webapp:
    image: 'kiujep/facilities:latest'
    depends_on:
      - postgresql
    environment:
      - DJANGO_PRODUCTION=True
      - DJANGO_SECRET_KEY="SECRET KEY"
      - DJANGO_DB_NAME=facilities
      - DJANGO_DB_USER=facilities
      - DJANGO_DB_PASSWORD=letmein
      - DJANGO_DB_HOST=postgresql
      - DJANGO_DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8000
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - "./media:/facility/media"
    restart: always

  postgresql:
    image: 'bitnami/postgresql:15'
    environment:
      - POSTGRESQL_USERNAME=facilities
      - POSTGRESQL_PASSWORD=letmein
      - POSTGRESQL_DATABASE=facilities
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - 'postgresql_initdb:/docker-entrypoint-initdb.d'
      - 'postgresql_pre_initdb:/docker-entrypoint-preinitdb.d'
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always



volumes:
  postgresql_data:
    driver: local
  postgresql_initdb:
    driver: local
  postgresql_pre_initdb:
    driver: local

